### ISSUE TITLE
Violation of license / Violation de la licence

### ISSUE THREAD

**Issue by maym2104** [anault/ift615_tp1#1]
_Le français suit._

According to the pacman projects license:
> Licensing Information:  You are free to use or extend these projects for educational purposes provided that (1) **you do not distribute or publish solutions**, (2) you retain this notice, and (3) you provide clear attribution to UC Berkeley, including a link to http://ai.berkeley.edu.

Publishing your solution thus violates the license. Authors of the projects have been notified about this. Could you therefore make this repo private, or save a local copy and delete this repo?

Notice that actions will be undertaken whether you accept or not to take down this repository yourself. Many universities still use the pacman projects and public solutions really complicates management of plagiarism cases. 

Thank you for your consideration.

-----------------------------------------------------------------------------------------------

Selon la licence des _Pacman projects_:
> Licensing Information:  You are free to use or extend these projects for educational purposes provided that (1) **you do not distribute or publish solutions**, (2) you retain this notice, and (3) you provide clear attribution to UC Berkeley, including a link to http://ai.berkeley.edu.

La publication de votre solution entraîne donc la violation de cette licence. Les auteurs des projets ont été avertis. Pourriez-vous donc rendre ce dépôt privé, ou sauvegarder une copie locale puis supprimer ce dépôt?

Notez bien que des démarches seront entreprises peu importe si vous acceptez ou non de supprimer ce dépôt vous-même(s). Beaucoup d'universités (dont l'Université de Sherbrooke) utilise encore ces projets et la disponibilité de solutions publiques compliquent grandement la gestion des cas de plagiat.

Merci pour votre considération.

**Comment by anault** [comment]
Repo is now private.
